import logging
import re
import sys

logger = logging.getLogger(__name__)

from typing import List

import pandas as pd
import pymupdf4llm
# import pymupdf
# from emoji import analyze
# from lxml import etree as ET
from bs4 import BeautifulSoup
# from mrkdwn_analysis import MarkdownAnalyzer
from pypdf import PdfReader

from FilePathsUrls import FilePaths
from PublicationDownloadServices import PublicationLog



# from tika import parser




class PublicationParser(PublicationLog):

    def __init__(self):

        self.has_acknowledgment = False
        self.is_fac_acknowledged = False
        self.is_fac_suspected = False

        self.ack_text = ''

        super().__init__()


    def _parse_xml_for_ack(self) -> None:

        xml_fullpath = FilePaths.xml_dir_fullpath / f'{self.pmid}_{self.pmcid}_pmh.xml'

        with open(xml_fullpath, 'r') as xml_file:
            xml_parsed = BeautifulSoup(xml_file, features="lxml")
        if xml_parsed.ack:
            self.ack_text = xml_parsed.ack.p.get_text()

    def _parse_pdf_for_ack(self) -> None:

        pdf_fullpath = FilePaths.pdf_dir_fullpath.glob(f'{self.pmid}*.pdf')

        for pdf_file_path in pdf_fullpath:

            md_text = pymupdf4llm.to_markdown(pdf_file_path)

            # with open('test.md', 'wb') as test_file:
            #     test_file.write(md_text.encode('utf-8', errors='ignore'))

            # Generated by Chat-GPT
            ack_pattern =  r"""
                            (?:\*\*)?\s*acknowledg(?:e)?ments?\s*(?:\*\*)?   # Überschrift
                            \s*
                            ([\s\S]*?)                                      # NUR der Inhalt
                            (?=                                             # Stop (Lookahead!)
                            \n\s*(?:\*\*[A-Z][A-Z\s]+\*\*|[A-Z][A-Z\s]{3,}\s*$)  # nächster Titel
                            | \n\s*\n\s*\n                                # ≥2 Leerzeilen
                            | $                                           # Dateiende
                            )
                            """

            ack_match = re.search(ack_pattern, md_text, re.I | re.S | re.X)

            if ack_match:
                self.ack_text = ack_match.group(1).strip()
                self.has_acknowledgment = True


            # analyzer = MarkdownAnalyzer('test.md')
            # paragraphs = analyzer.identify_paragraphs()
            #
            # for value in paragraphs.values():
            #     for paragraph in value:
            #         # print(paragraph)
            #         # if paragraph.startswith('ACKNOWLEDGMENTS'):
            #         if 'ackn' in paragraph.lower():
            #             print(paragraph)
            #             break
            #     else:
            #         print('No acknowledgments found...')


            # reader = PdfReader(pdf_file_path)
            # text = "\n".join(p.extract_text() for p in reader.pages)
            #
            # ackn_text = text[text.lower().find('ackn') - 50 :]
            # print(ackn_text)
            # with open('test.txt', 'w') as test_file:
            #     test_file.write(ackn_text)

            # print(ackn_text[0:50].rfind("\n"), ackn_text[50:].find('\n'))
            # print(ackn_text[50 - ackn_text[0:50].rfind("\n"):50 + ackn_text[50:].find('\n')])


    def parse_fulltext_for_ack(self) -> None:

        # Parse the fulltext for the acknowledgement section
        if self.is_xml_fulltext:
            self._parse_xml_for_ack()
        if self.is_pdf_fulltext:
            self._parse_pdf_for_ack()

        # If found, set flag and write it to file
        if self.ack_text:
            self.has_acknowledgment = True

            ack_result_fullpath = FilePaths.ack_dir_fullpath / f'{self.pmid}_ack.txt'

            with open(ack_result_fullpath, 'wb') as ack_file:
                ack_file.write(self.ack_text.encode('utf-8', errors='ignore'))



    # Compound the necessary information into a csv-string to write to the log.
    def list_publication_info(self) -> List[str]:
        # citation_file_name, Pubmed Id, PMC Id, DOI, as_xml, as_pdf, as_html, fac_acknowledged, fac_suspected
        data = [self.citation_file_name,
                self.pmid,
                self.pmcid,
                self.doi,
                str(self.is_xml_fulltext),
                str(self.is_pdf_fulltext),
                str(self.is_html_fulltext),
                str(self.is_fac_acknowledged),
                str(self.is_fac_suspected),
                ]

        return data

# Converts String to boolean
def str2bool(input_str: str) -> bool:
    if input_str == 'True':
        return True
    if input_str == 'False':
        return False
    raise ValueError('Invalid input_str: Must be "True" or "False"')


def configure_results_logger() -> logging.Logger:
    logging.basicConfig(level=logging.INFO,
                        handlers=[logging.FileHandler(FilePaths.results_log_fullpath),
                                  logging.StreamHandler(sys.stdout),
                                  ]
                        )
    return logger


def populate_results_log(parsed_pubs:List[PublicationParser], logger: logging.Logger) -> None:

    fulltext_pubs = [pub for pub in parsed_pubs if pub.has_fulltext]

    for pub in fulltext_pubs:
        if pub.has_acknowledgment:

            ack_result_fullpath = FilePaths.ack_dir_fullpath / f'{pub.pmid}_ack.txt'
            logger.info(f'{pub.pmid} has acknowledgments, saved to: {ack_result_fullpath}')
        else:
            logger.info(f'{pub.pmid} has no acknowledgments.')

    logger.info('************************************************************')

    ack_count = len([True for pub in parsed_pubs if pub.has_acknowledgment])
    pubs_wo_ack = [pub for pub in parsed_pubs if (not pub.has_acknowledgment and pub.has_fulltext)]
    logger.info(f'{ack_count}/{len(fulltext_pubs)} publications have acknowledgements.')

    for pub in pubs_wo_ack:
        logger.info(f'Missing acknowledgements: {pub.citation_file_name}, PMID: {pub.pmid}, DOI: {pub.doi}')
    return

#
#     # Compound the necessary information into a csv-string to write to the log.
#     def log_csv_string(self):
#         # citation_file_name, as_xml, as_pdf, fac_acknowledged, fac_suspected\n'
#         data = [str(self.file_name), str(self.is_pmc_xml_fulltext), str(self.is_kops_pdf_fulltext), str(self.is_fac_acknowledged), 'None\n']
#         return ','.join(data)
#
#     # Copy the relevant publication files to a subdirectory (Citations (xml and ris), fulltext, Acknowledgement snippet)
#     def copy_pub_with_ack(self):
#         pub_ack_path = pub_dir / ack_subdirectory
#         if not pub_ack_path.is_dir():
#             pub_ack_path.mkdir()
#         self._store_ack_text(pub_ack_path)
#         shutil.copy(pub_dir / self.file_name, pub_ack_path)
#         shutil.copy(self.pub_fulltext_file_path, pub_ack_path)
#         shutil.copy((pub_dir / self.file_name).with_suffix('.ris'), pub_ack_path)



# Adapt accordingly
search_term_list = ['BIC', 'Bioimaging']
ack_term_list = ['we thank', 'like to thank', 'we acknowledge', 'assisted by', 'thankful', 'grateful']


if __name__ == '__main__':

    # Configure the logger fo write the results log
    configure_results_logger()

    # Read the publication information
    with FilePaths.publication_log_fullpath.open(mode='r') as csv_file:
        publication_df = pd.read_csv(csv_file, header=0)

    parsed_publications = []

    # Create a publication parser for each entry
    for index, series in publication_df.iterrows():
        publication_parser = PublicationParser()
        publication_parser.initialize_from_log_entry(series.to_dict())
        publication_parser.parse_fulltext_for_ack()
        parsed_publications.append(publication_parser)

    populate_results_log(parsed_publications, logger)



